### ISSUE TITLE
Julia lexer for editor

### ISSUE THREAD

**Issue by Alexey-T** [tlienart/LiveServer.jl#113]
I see you 've starred CudaText, it has the Julia lexer in addons. Is it working OK, or has some issues? @tlienart

**Comment by tlienart** [comment]
Hello! CudaText was mentioned here: https://discourse.julialang.org/t/is-anyone-using-textadept-as-their-editor-of-choice-for-julia/41255/39 so I gave it a shot (I'm always curious about new editors which are simple and fast and I think the people in that thread are too).

At the moment I've not used CudaText for Julia (Atom and VS Code provide an integration Julia REPL which helps *a lot* with development) but I have used it with other languages such as Python and it worked great for me, thanks for making and open-sourcing this, it's awesome!

**Comment by tlienart** [comment]
I just tried opening a Julia project, here are some quick comments (I could make those in your repo if you preferred):

![Screenshot 2021-01-24 at 17 32 16](https://user-images.githubusercontent.com/10897531/105636775-24b02500-5e6a-11eb-91b4-33efae5d27c6.png)

--> ideally the `:name` should be highlighted as strings, the `const` keyword should be highlighted too as well as function indicators (like `LittleDict`) though that last one matters less.

![Screenshot 2021-01-24 at 17 33 35](https://user-images.githubusercontent.com/10897531/105636814-4e694c00-5e6a-11eb-958d-bef1edb223e6.png)

--> keywords like `function`, `if`, `end`, etc should be highlighted, functions should ideally be highlighted, modules (e.g. `Base.` and `Core.` should too + `missing` keyword

![Screenshot 2021-01-24 at 17 34 54](https://user-images.githubusercontent.com/10897531/105636858-7ce72700-5e6a-11eb-84cb-0a335fbaccd7.png)

--> text between `"""` should be highlighted as string, `#= ... =#` indicates a multi-line comments

I could give you more detailed feedback on this at the main repo if that's useful?

**Comment by Alexey-T** [comment]
yes, please copy that into my repo - https://github.com/Alexey-T/CudaText/issues
to not miss it. or I can copy this?
