### ISSUE TITLE
Confused with paths and script files

### ISSUE THREAD

**Issue by cserteGT3** [tlienart/LiveServer.jl#115]
I'm trying to use LiveServer within Docker, but getting an error, that I don't understand. I started creating an MWE and realized that I don't need Docker to confuse myself.
I have the MWE repo here: https://github.com/cserteGT3/Documentertest

From the root of the repository the following works:
```
Documentertest>julia --project=docs -e "using LiveServer; servedocs()"
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: running doctests.
[ Info: ExpandTemplates: expanding markdown templates.
[ Info: CrossReferences: building cross-references.
[ Info: CheckDocument: running document checks.
[ Info: Populate: populating indices.
[ Info: RenderDocument: rendering document.
[ Info: HTMLWriter: rendering HTML pages.
✓ LiveServer listening on http://localhost:8000/ ...
  (use CTRL+C to shut down)
```

But this doesn't:
```
Documentertest>julia docs\dockerhtml.jl
 Activating environment at `C:\path\to\Documentertest\docs\Project.toml`
ERROR: LoadError: could not open file C:\path\to\Documentertest\docs\docs\make.jl
Stacktrace:
 [1] include(::String) at .\client.jl:457
 [2] servedocs(; verbose::Bool, literate::String, doc_env::Bool, skip_dir::String, skip_dirs::Array{String,1}, foldername::String, buildfoldername::String, launch_browser::Bool) at C:\Users\username\.julia\packages\LiveServer\4Y1VV\src\utils.jl:150
 [3] servedocs() at C:\Users\u\.julia\packages\LiveServer\4Y1VV\src\utils.jl:134
 [4] top-level scope at C:\path\to\Documentertest\docs\dockerhtml.jl:6
 [5] include(::Function, ::Module, ::String) at .\Base.jl:380
 [6] include(::Module, ::String) at .\Base.jl:368
 [7] exec_options(::Base.JLOptions) at .\client.jl:296
 [8] _start() at .\client.jl:506
in expression starting at C:\path\to\Documentertest\docs\dockerhtml.jl:6
```
I'm using Win10, Julia v1.5.3, the latest LiveServer and Documenter 0.25.5.

In my eyes the script should do exactly the same, as the evaluated expression. Is this a bug or am I missing something?

**Comment by tlienart** [comment]
> `ERROR: LoadError: could not open file C:\path\to\Documentertest\docs\docs\make.jl` 

you can see the error there with a doubling of `docs/` path. Do you use `servedics(..)` indicating what the `foldername=...` is? if not, you should try that.

The default mode is that `docs` is the path in the current directory (from which you execute the Julia command). If you want this to be different, then you should do `servedocs(foldername="path/that/contains/docs")` (adapted to windows).

**Comment by tlienart** [comment]
These are the lines that will take the path and which expect to be able to find a `make.jl` : https://github.com/tlienart/LiveServer.jl/blob/2b9dae604439aa5c860dbaf51cbf3f1a85abe2a3/src/utils.jl#L51-L55

**Comment by cserteGT3** [comment]
Here's the script I tried now (with `foldername="docs")`:
```julia
using Pkg
Pkg.activate("docs")
#Pkg.instantiate()

using LiveServer
servedocs(foldername="docs")
```
But i gives the same error, as above.
The lines you mentioned (in `scandocs`) run fine. With modifying a little bit with debug statements:
```julia
    src = joinpath(foldername, "src")
    @show foldername
    @show src
    if !(isdir(foldername) && isdir(src))
        @error "I didn't find a $foldername/ or $foldername/src/ folder."
    end
    makejl = joinpath(foldername, "make.jl")
    @show makejl
```
I got:
```
Documentertest>julia docs\dockerhtml.jl
 Activating environment at `C:\path\to\Documentertest\docs\Project.toml`
foldername = "docs"
src = "docs\\src"
makejl = "docs\\make.jl"
ERROR: LoadError: could not open file C:\path\to\Documentertest\docs\docs\make.jl
Stacktrace:
 [1] include(::String) at .\client.jl:457
 [2] servedocs(; verbose::Bool, literate::String, doc_env::Bool, skip_dir::String, skip_dirs::Array{String,1}, foldername::String, buildfoldername::String, launch_browser::Bool) at C:\Users\cstamas\.julia\dev\LiveServer\src\utils.jl:153
 [3] top-level scope at C:\Users\username\Documents\GIT\Documentertest\docs\dockerhtml.jl:6
 [4] include(::Function, ::Module, ::String) at .\Base.jl:380
 [5] include(::Module, ::String) at .\Base.jl:368
 [6] exec_options(::Base.JLOptions) at .\client.jl:296
 [7] _start() at .\client.jl:506
in expression starting at C:\Users\username\Documents\GIT\Documentertest\docs\dockerhtml.jl:6
```
which shows that `scan_docs!` finds the files and folders just fine.
I suppose something "is wrong" with the `Main.include(makejl)`. From its docs:
> During including, a task-local include path is set to the directory containing the file. 

Maybe this behavior is what creates the duplicate `docs` in the path. Using an absolute path (`Main.include(abspath(makejl))`) solves this problem.

**Comment by cserteGT3** [comment]
#116 implemented the workaround.
Thanks for quickly reviewing, releasing and registering it!
