### ISSUE TITLE
[FR] Option to watch more directories in servedocs

### ISSUE THREAD

**Issue by fredrikekre** [tlienart/LiveServer.jl#126]
When working with docs for a package it would be useful to also watch the source files if you update docstrings for example. Currently you have to (i) make change to the source file, (ii) update a watched file in `docs/src` to see updates.

You also need Revise to update the docstrings etc, so e.g. adding `using Revise; Revise.revise()` to the top of the `make.jl` file enables a *very* smooth doc writing workflow!

**Comment by tlienart** [comment]
Sounds good to me, I'm translating your suggestion into

* adding all `.jl` files in `src/` by default to the watched files when using `servedocs`
* suggesting putting `using Revise; Revise.revise()` in the `make.jl` when using `servedocs`

**Comment by fredrikekre** [comment]
Yea, having it default would be even smoother of course, but just having the option of passing e.g. `watch_files="src"` would be great!
