### ISSUE TITLE
Error with dir listing

### ISSUE THREAD

**Issue by tlienart** [tlienart/LiveServer.jl#131]
@tlienart 
I test v0.7.2, but the function is abnormal,, 

serve(host="0.0.0.0", port=8002, dir="/data")
![image](https://user-images.githubusercontent.com/12711073/157042631-17210c20-02ec-4b8f-9cb1-c2738473a4eb.png)
click the `zhangyong` dir:
![image](https://user-images.githubusercontent.com/12711073/157042684-b9415285-e64b-42e7-aea6-6ee1376d52e1.png)

_Originally posted by @zsz00 in https://github.com/tlienart/LiveServer.jl/issues/130#issuecomment-1060684298_

@zsz00 would you mind sharing the tree of the directory you worked with so I can try reproduce something similar? thanks for the bug report, will try to get this fixed quickly

(PS: are you on Windows? maybe this is the source of the issue, I tried a bunch of things here and everything seems to work fine but I'm on Unix)

**Comment by zsz00** [comment]
```
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cascadelake)

```

![image](https://user-images.githubusercontent.com/12711073/157083960-28851f4b-2c4e-4b3e-a3bb-9e7107f714c5.png)

![image](https://user-images.githubusercontent.com/12711073/157084032-c6e8184b-f2f1-4ca4-8fda-f629610d3d8c.png)

![image](https://user-images.githubusercontent.com/12711073/157084129-b88c0c1d-7736-4a63-9bf3-54b91bcf4299.png)

**Comment by tlienart** [comment]
@zsz00 could you please try the master branch? this should be fixed now, I'll do a patch release once you've confirmed that things work on your side.

Thanks for flagging the bug, it was just a case of not forgetting to remove `CONTENT_DIR[]` from the path.

**Comment by zsz00** [comment]
I had try the master branch, is work good. 

a small problem is open a text file , meet encodeing problem.

the text is utf-8 chinese 
![image](https://user-images.githubusercontent.com/12711073/157159481-d993d1b4-e351-444a-95f4-afb7690041fb.png)

**Comment by tlienart** [comment]
Thanks! Could you open another issue for this? I'm not sure how to fix that, maybe there's another fallback MIME other than `text/plain` that should be used.

I'll do a release with the bug fix in the meantime

**Comment by zsz00** [comment]
ok,

**Comment by zsz00** [comment]
I hope that when this issue can be closed, this issue can be deleted, because the pictures inside contain a lot of information about my machine .

**Comment by zsz00** [comment]
It's fine, thanks...
