### ISSUE TITLE
dir list page open a text file,  encodeing problem

### ISSUE THREAD

**Issue by zsz00** [tlienart/LiveServer.jl#132]
a small problem is open a text file , meet encodeing problem.

the text is utf-8 chinese 
![image](https://user-images.githubusercontent.com/12711073/157159481-d993d1b4-e351-444a-95f4-afb7690041fb.png)

**Comment by tlienart** [comment]
this should now be fixed in the latest patch release, could you please try it on your side and let me know if it works for you?
