### ISSUE TITLE
Redirect to URL with trailing slash if directory

### ISSUE THREAD

**Issue by mortenpi** [tlienart/LiveServer.jl#135]
I believe LiveServer should redirect to a URL with a trailing slash if it is a directory. Currently (LiveServer 0.8.0), if you navigate to e.g. `/docs/build`, it will serve the `/docs/build/index.html` file on that URL, but it breaks relative URLs in the HTML (e.g. `assets/foo.css` gets interpreted as `/docs/assets/foo.css`, rather than `/docs/build/assets/foo.css`).

My impression is that web servers generally do a 301-redirect to e.g. `/docs/build/` in that circumstance. A case in point, if you request such a URL from GitHub Pages, you get this response:

```
$ curl -I https://juliadocs.github.io/Documenter.jl/stable
HTTP/2 301 
server: GitHub.com
content-type: text/html
location: https://juliadocs.github.io/Documenter.jl/stable/
```

**Comment by tlienart** [comment]
Thanks for flagging this. Would you have an example repo or a set of steps that I can follow to reproduce this?

The `servedocs()` function in LiveServer seems to work fine as far as I can see and loads assets properly but it's likely I'm limited by my own example in which there are things like `../../assets/foo.png` which seem to resolve fine.

**Comment by tlienart** [comment]
I'm not immediately clear on how to solve this so if someone wants to give it a shot they can, I won't have a lot of time until probably the summer to look into this. 

The logic potentially to adjust would be 

1. `get_fs_path` in server.jl potentially based on the requested path `req_path`
2. `serve_file` in server.jl which applies different logic in the different scenarios
3. `serve` the logic with `RequestHandlerFunction` if there needs to be some pre processing of the request. 

something to check as well is that if you're in the root folder i.e. you `cd` to the folder so that you're effectively in root (e.g. in `build/`) then there isn't an issue. This is why `servedocs` works fine I guess. So maybe this can be simulated, maybe via `CONTENT_DIR`. 

Just thoughts, I unfortunately haven't had a lot of time to look into this.

**Comment by mortenpi** [comment]
A small stopgap UX improvement related to this: if we could have the directory index page generate URLs with a trailing slash for directories, then I think it would remove 90%+ of the cases where I actually run into this in practice.

My workflow is to have a single persistent LiveServer instance running, serving multiple different repositories and worktrees, and so I use the index pages to navigate around. But once I'm in the `docs/` directory and click on the `build/` link, it breaks and I have to manually add a slash to the URL.

**Comment by mortenpi** [comment]
@tlienart I love #144, thank you! It's a massive QoL improvement for my use case!

I was wondering though if it might be worth keeping this issue open until the redirect is also implemented? I would still argue that the redirect would be the more correct behavior (to be consistent with other webservers). While I don't really run into it anymore, if you manually navigate to a URL without a trailing `/` (or have some link that does), you still get the original issue.

**Comment by tlienart** [comment]
Great!

re your comment, if you go to like `localhost:8000/build` it does redirect you (silently) to `build/` doesn't that sort out the issue you mentioned? what I mean by silently is that it won't appear in the URL, but what will be considered by LiveServer is `build/`.

Or maybe could you let me know a set of steps that highlights the problem? maybe we can open a dedicated issue for it

**Comment by mortenpi** [comment]
I am not actually sure what you mean by silently redirecting, unless you just mean that if you navigate to `foo`, it will actually serve `foo/` -> `foo/index.html`? But this was also happening before #144? The problem is that the browser doesn't know that, and so can't resolve any of the the relative URLs correctly. The server should be issuing a `301 Redirect`, so that the URL in the browser would actually get updated.

In any case, as they say, an MWE is worth a thousand issues :slightly_smiling_face: If you clone [this gist](https://gist.github.com/mortenpi/6ba254dd107017900e69dc105a39a33f) into `ls-135-repro/`:

```bash
git clone git@gist.github.com:6ba254dd107017900e69dc105a39a33f.git ls-135-repro
```

then do `LiveServer.serve()` still in the parent directory, and then navigate to `http://localhost:8000/ls-135-repro` in your browser, you'll see that the image won't load. It will load fine if you go to `http://localhost:8000/ls-135-repro/`.

Side note: I noticed that the links generated by `LiveServer.example()` all have absolute URLs (i.e. starting with `/`), so the example won't work unless you `serve()` from within the `example/` directory (so I couldn't actually use them to demonstrate this issue). In principle, all those URLs could be relative I think?
