### ISSUE TITLE
Hope serve() page add function of return to parent directory

### ISSUE THREAD

**Issue by zsz00** [tlienart/LiveServer.jl#137]
Hope serve() page add function of return to parent directory

add .. or parent directory button  on head of page

![image](https://user-images.githubusercontent.com/12711073/167629721-7de8d903-b4b6-44ef-b334-d7d39779521d.png)

**Comment by tlienart** [comment]
This is about to be patch-releasedm I hope the small changes I did to your PR are fine with you. It looks like this:
<img width="325" alt="Screenshot 2022-05-11 at 16 17 19" src="https://user-images.githubusercontent.com/10897531/167871738-fbf2a7cd-5f27-45d4-83d4-5013c0f07563.png">

**Comment by zsz00** [comment]
cool !!!
