### ISSUE TITLE
LiveServer not rendering mp4 videos in Safari

### ISSUE THREAD

**Issue by luraess** [tlienart/LiveServer.jl#151]
Video animations in `.mp4` do not display when serving a website on localhost in the Safari (tested in macOS 10.15.7, Safari 15.6.1). Videos are embedded as
```
~~~
<center>
  <video width="80%" autoplay loop controls src="/assets/porous_convection_2D.mp4"/>
</center>
~~~
```
All works fine for the website version deployed on GH pages, and locally on other browsers (tested also with Chrome).

It is seemingly a Safari only issue. From web search, it may be that there is an issue such as https://stackoverflow.com/a/36299252.

Webpage of interest: https://github.com/eth-vaw-glaciology/course-101-0250-00/blob/main/website/index.md

**Comment by tlienart** [comment]
@fonsp or @quinnj could I maybe get your input here please? I'm not sure what's the best approach, whether it's to return a 206 or a custom header when serving the file. 

Here's a [demo repo](https://github.com/tlienart/sbx-mp4), serving with LiveServer and opening with Safari will fail, with FF, Chrome and co, will work fine. SO seems to mention returning a 206 with a range but I'm not sure about any of this.

Thanks in advance

**Comment by fonsp** [comment]
One difference between Safari and the rest is that Safari will _only_ render a video if the web server supports range requests: an HTTP GET request with a `Range` header ([see MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests)). 

So to support mp4 in safari, LiveServer should implement the range request protocol, which means checking for the `Range` request header, responding with partial data, adding the `Content-Length` and `Content-Range` headers to the response and the 206 status code. I think it's fine to skip multiple range support and conditional range support.

Here is an example of the network tab in safari when watching a video:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/6933510/191546568-3462e1d2-5b37-4005-9ff5-b210306a0734.png">
