### ISSUE TITLE
I wish Ctrl+C worked

### ISSUE THREAD

**Issue by cormullion** [tlienart/LiveServer.jl#164]
This is probably a VS-Code or Julia issue really, but LiveServer.jl doesn't like to quit (a commendable attitude in most other circumstances):

```
→ Starting the server...
[ Info: Listening on: 127.0.0.1:8000, thread id: 1
✓ LiveServer listening on http://localhost:8000/ ...
  (use CTRL+C to shut down)
→ page updated [✓] 
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

I know I can just kill the entire terminal, but I always worry that I might damage a file or something...

**Comment by tlienart** [comment]
Oh wow... I use it daily and even though it sometimes requires a double tap, 50x should definitely kill the job...

Can you give some context on what you were doing and what system you were on? (Eg was code being executed in the background, is this reproducible in your case etc)

**Comment by cormullion** [comment]
Hi! So I tried to reproduce yesterday's environment today in a new VSCode session, and (of course) it's started behaving itself now. I'm using VSCode on Mac, running Franklin in a terminal, editing various files in the editing area on the left. Using Julia 1.9.0 and Franklin v0.10.84.

I'm guessing that VSCode just got tired eventually, and started playing up. If it starts again, I'll do some more investigation.

Thanks!

**Comment by tlienart** [comment]
Thanks @cormullion , I did experience an issue with LiveServer that was not identical but maybe related to what you observed with `1.9.0`, updating to `1.9.1` did seem to help 🤷 . 

Are you using the latest LiveServer too? (`1.2.0`). 

I'll close this for now.

(PS: catching interruptexception cleanly is probably worth a dedicated julia package at this point...)
